
mybatis:
    type-aliases-package: inc.develop.spring
    mapper-locations: classpath*:/mapper/**/*-mapper.xml
---
spring:
    profiles: dev
    datasource: 
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_db?characterEncoding=UTF-8&amp;serverTimezone=UTC&amp
        username: root
        password: 1234
server:
    port: 18080
---
spring:
    profiles: prod
    datasource: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_db?characterEncoding=UTF-8&amp;serverTimezone=UTC&amp
        username: root
        password: 1234
server:
    port: 18080